src/Entity/UserProfile.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserProfileRepository")
 */
class UserProfile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UserProfile", inversedBy="friendsReceived")
     * @ORM\JoinTable(name="friendship",
     * joinColumns={
     *     @ORM\JoinColumn(name="sender_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="receiver_id", referencedColumnName="id")
     *   }
     * )
     */
    private $friendsRequested;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UserProfile", mappedBy="friendsRequested")
     */
    private $friendsReceived;

    public function __construct()
    {
        $this->friendsRequested = new ArrayCollection();
        $this->friendsReceived = new ArrayCollection();
    }

    public function getFriends(): ?array
    {
        return array_merge(
            $this->getFriendsRequested()->toArray(),
            $this->getFriendsReceived()->toArray()
        );
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFriendsRequested(): Collection
    {
        return $this->friendsRequested;
    }

    public function addFriendsRequested(self $friendsRequested): self
    {
        if (!$this->friendsRequested->contains($friendsRequested)) {
            $this->friendsRequested[] = $friendsRequested;
        }

        return $this;
    }

    public function removeFriendsRequested(self $friendsRequested): self
    {
        if ($this->friendsRequested->contains($friendsRequested)) {
            $this->friendsRequested->removeElement($friendsRequested);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFriendsReceived(): Collection
    {
        return $this->friendsReceived;
    }

    public function addFriendsReceived(self $friendsReceived): self
    {
        if (!$this->friendsReceived->contains($friendsReceived)) {
            $this->friendsReceived[] = $friendsReceived;
            $friendsReceived->addFriendsRequested($this);
        }

        return $this;
    }

    public function removeFriendsReceived(self $friendsReceived): self
    {
        if ($this->friendsReceived->contains($friendsReceived)) {
            $this->friendsReceived->removeElement($friendsReceived);
            $friendsReceived->removeFriendsRequested($this);
        }

        return $this;
    }

}

src/Form/UserProfileType.php
<?php

// src/Form/UserProfileType.php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class UserProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class)
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('submit', SubmitType::class, ['label' => 'Register']);
    }
}

?>

src/Controller/HomeController.php
<?php

// src/Controller/HomeController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    public function helloWorld()
    {
        return new Response('<html><body><h1>Hello World</h1></body></html>');
    }
}

?>

src/Controller/ProfileController.php
<?php

// src/Controller/ProfileController.php
namespace App\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\UserProfile;
use App\Form\UserProfileType;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile/{id}", name="profile_view")
     */
    public function viewProfile($id = "1")
    {
        $userId = (int) $id;
        $user = $this->getDoctrine()
                ->getRepository(UserProfile::class)
                ->find($userId);

        $model = array('user' => $user);
        $view = 'profile.html.twig';
        return $this->render($view, $model);
    }

    /**
     * @Route("/register", name="profile_new")
     */
    public function newProfile(Request $request)
    {
        $userProfile = new UserProfile();
        $form = $this->createForm(UserProfileType::class, $userProfile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            $userProfile = $form->getData();
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($userProfile);
            $entityManager->flush();

            return $this->redirectToRoute('profile_success');
        }        

        $view = 'register.html.twig';
        $model = array('form' => $form->createView());
        return $this->render($view, $model);
    }

    /**
     * @Route("/success", name="profile_success")
     */
    public function successProfile(Request $request)
    {
        $view = 'success.html.twig';
        $model = array();
        return $this->render($view, $model);
    }
}

?>

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{% block title %}Welcome!{% endblock %}</title> <link rel="stylesheet" 
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
Friendface
</a>
                </div>
            </div>
        </nav>
        <main class="container">
            {% block body %}{% endblock %}
        </main>
<script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/profile.html.twig
{% extends "base.html.twig" %}
{% block title %}Profile | Friendface{% endblock %}
{% block body %}
    <div class="row">
        This is the profile page of {{ user.username }} ({{ user.email }}) who has {{ user.friends|length}} friends.
    </div>
    <div class="row">
        <ul>
            {% for friend in user.friends %}
                <li>{{ friend.username }}</li>
            {% endfor %}
</ul> </div>
{% endblock %}

templates/register.html.twig
{% extends "base.html.twig" %}

{% block title %}Register | Friendface{% endblock %}

{% block body %}
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/success.html.twig
{% extends "base.html.twig" %}
{% block title %}Success | Friendface{% endblock %}
{% block body %}
    <div class="row">
        New user registered successfully!
    </div>
{% endblock %}